### ISSUE TITLE
can't find org.jooq:jooq:jar:3.18.0-SNAPSHOT

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/sql2cypher#1]
Would the version on maven central work too @lukaseder ? 3.17.7 ?

**Comment by jexp** [comment]
Ok, I'll build jOOQ locally for now. /cc @michael-simons 
 
> Once we release, we'll use a non-snapshot jOOQ version. For now, the snapshot version from https://github.com/jOOQ/jOOQ is required in order to be able to move faster.

**Comment by lukaseder** [comment]
It would in principle, but 3.18 has tons of improvements in the `QOM` API, which are of interest to this utility here, so it would be a pity not to profit from that already.

Plus, I'm expecting early feedback from you folks to have lots of influence for the `QOM` API as well, and maybe even for the parser, so as we start this project, we can move more quickly if we work with jOOQ 3.18.0-SNAPSHOT, rather than 3.17.x. Once this is ready to be released and used by the community, obviously, we'll only depend on stable releases.

**Comment by jexp** [comment]
https://github.com/jOOQ/jOOQ/issues/14519
